steps:
  # Membuat image dengan perintah "cloud build -t gcr.io/$PROJECT_ID/tcc-be ."
  # Project ID akan secara otomatis terisi ketika melakukan deploy di project yg dipilih
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tcc-be", "."]

  # Meng-upload/push image yg telah dibuat ke Artifact Registry
  # Pada bagian ini, dijalankan perintah "docker push 'gcr.io/$PROJECT_ID/tcc-be'"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-be"]

  # Melakukan deploy ke cloud run menggunakan image yg telah di-upload/push pada langkah sebelumnya
  # Removed --port flag as Cloud Run will auto-detect from EXPOSE in Dockerfile
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "be",
        "--image",
        "gcr.io/$PROJECT_ID/tcc-be",
        "--timeout",
        "1000s",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

# Log hanya akan disimpan di Google Cloud Logging
# Log tidak akan disimpan di Google Cloud Storage (butuh hak akses).
options:
  logging: CLOUD_LOGGING_ONLY